# Generated by Django 4.1.1 on 2022-10-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='body',
        ),
        migrations.AddField(
            model_name='issue',
            name='composer_spotlight',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='never_gets_old',
            field=models.TextField(blank=True),
        ),
    ]
