# Generated by Django 4.1.1 on 2022-10-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_issue_body_issue_composer_spotlight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='composer_spotlight',
            new_name='composer_spotlight_body',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='first_impressions',
            new_name='first_impressions_body',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='never_gets_old',
            new_name='never_gets_old_body',
        ),
        migrations.AddField(
            model_name='issue',
            name='composer_spotlight_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='composer_spotlight_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='never_gets_old_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='never_gets_old_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
