# Generated by Django 4.1.1 on 2022-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_rename_composer_spotlight_issue_composer_spotlight_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='first_impressions_body',
            new_name='first_impressions_michael_body',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='first_impressions_desc',
            new_name='first_impressions_michael_desc',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='first_impressions_title',
            new_name='first_impressions_michael_title',
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_robert_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_robert_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_robert_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_stephen_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_stephen_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_stephen_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
