# Generated by Django 4.1.2 on 2022-10-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_rename_first_impressions_body_issue_first_impressions_michael_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposerSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstImpressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=200, null=True)),
                ('first_desc', models.CharField(max_length=200, null=True)),
                ('first_body', models.TextField(blank=True)),
                ('second_title', models.CharField(max_length=200, null=True)),
                ('second_desc', models.CharField(max_length=200, null=True)),
                ('second_body', models.TextField(blank=True)),
                ('third_title', models.CharField(max_length=200, null=True)),
                ('third_desc', models.CharField(max_length=200, null=True)),
                ('third_body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeverGetsOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='composer_spotlight_body',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='composer_spotlight_desc',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='composer_spotlight_title',
        ),
    ]
