# Generated by Django 4.1.2 on 2022-10-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_remove_issue_first_impressions_michael_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='composer_spotlight',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='first_impressions',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='never_gets_old',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='summary',
        ),
        migrations.AddField(
            model_name='issue',
            name='composer_spotlight_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='composer_spotlight_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='composer_spotlight_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='never_gets_old_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='never_gets_old_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='never_gets_old_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ComposerSpotlight',
        ),
        migrations.DeleteModel(
            name='FirstImpressions',
        ),
        migrations.DeleteModel(
            name='NeverGetsOld',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AddField(
            model_name='issue',
            name='Summary',
            field=models.TextField(blank=True),
        ),
    ]
