# Generated by Django 4.1.2 on 2022-10-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_rename_summary_issue_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstimpressions',
            name='first_impressions',
        ),
        migrations.AddField(
            model_name='issue',
            name='first_impressions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.firstimpressions'),
        ),
    ]
