# Generated by Django 4.1.2 on 2022-10-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_remove_issue_composer_spotlight_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='first_impressions',
        ),
        migrations.DeleteModel(
            name='FirstImpressions',
        ),
        migrations.AddField(
            model_name='element',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='newsletter.issue'),
        ),
    ]
