# Generated by Django 4.1.2 on 2022-10-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_alter_element_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='title',
        ),
        migrations.AddField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
