# Generated by Django 4.1.2 on 2022-10-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_remove_issue_summary_remove_issue_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='element',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='newsletter.issue'),
        ),
    ]
