# Generated by Django 4.1.2 on 2022-10-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0015_element_image_alter_element_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='content',
            new_name='text',
        ),
    ]
