# Generated by Django 4.1.2 on 2022-10-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0019_rename_text_element_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='content',
            new_name='text',
        ),
    ]
