# Generated by Django 4.1.2 on 2022-10-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0023_alter_element_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
