# Generated by Django 4.1.2 on 2022-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0024_element_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='link',
            new_name='link_name',
        ),
        migrations.AddField(
            model_name='element',
            name='link_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
