# Generated by Django 4.1.2 on 2022-10-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0025_rename_link_element_link_name_element_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='newsletter.issue'),
        ),
        migrations.AlterField(
            model_name='element',
            name='link_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
